SOURCE_MYCITYAIR = "mycityair"
SOURCE_PLUMELABS = "plumelabs"
SOURCE_OPEN_METEO = "open_meteo"

CITY_BACKGROUND_SOURCES: tuple[str, ...] = (
    SOURCE_PLUMELABS,
    SOURCE_OPEN_METEO,
)

COLLECTION_ENABLED_SOURCES: tuple[str, ...] = (
    SOURCE_MYCITYAIR,
    SOURCE_PLUMELABS,
    SOURCE_OPEN_METEO,
)
