# Generated by Django 5.2.12 on 2026-03-31 08:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_len_hours', models.PositiveSmallIntegerField(default=72)),
                ('forecast_horizon_hours', models.PositiveSmallIntegerField(default=24)),
                ('master_row_count', models.PositiveIntegerField(default=0)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('feature_columns', models.JSONField(default=list)),
                ('target_columns', models.JSONField(default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('payload_npz', models.BinaryField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp_utc', models.DateTimeField(db_index=True)),
                ('values', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['timestamp_utc'],
            },
        ),
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_from_timestamp_utc', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('forecast_horizon_hours', models.PositiveSmallIntegerField(default=24)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='started', max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=128)),
                ('status', models.CharField(choices=[('training', 'Training'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='training', max_length=32)),
                ('input_len_hours', models.PositiveSmallIntegerField(default=72)),
                ('forecast_horizon_hours', models.PositiveSmallIntegerField(default=24)),
                ('feature_names', models.JSONField(default=list)),
                ('target_names', models.JSONField(default=list)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('history', models.JSONField(blank=True, default=dict)),
                ('checkpoint_blob', models.BinaryField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('source', models.CharField(db_index=True, max_length=64)),
                ('source_kind', models.CharField(blank=True, max_length=64)),
                ('station_id', models.CharField(blank=True, max_length=128)),
                ('station_name', models.CharField(blank=True, max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('observed_at_utc', models.DateTimeField(db_index=True)),
                ('time_bucket_utc', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('time_window_utc', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('metric', models.CharField(db_index=True, max_length=64)),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-observed_at_utc', 'source', 'metric'],
            },
        ),
    ]
