# Generated by Django 5.2.12 on 2026-03-31 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastrun',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forecastrecord',
            name='forecast_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='monitoring.forecastrun'),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='monitoring.datasetsnapshot'),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='model_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_runs', to='monitoring.modelversion'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['metric', 'observed_at_utc'], name='monitoring__metric_a135ef_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['source', 'observed_at_utc'], name='monitoring__source_c9afd8_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastrecord',
            index=models.Index(fields=['forecast_run', 'timestamp_utc'], name='monitoring__forecas_c0e6da_idx'),
        ),
    ]
