# Generated by Django 5.2.12 on 2026-04-02 05:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_rename_monitoring__status_6a6f6b_idx_monitoring__status_9b9d8b_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMonitoringTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('collect_observations', 'Collect observations'), ('build_dataset', 'Build dataset'), ('train_model', 'Train model'), ('generate_forecast', 'Generate forecast'), ('run_experiment', 'Run experiment')], db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('started', 'Started'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=32)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_monitoring_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_for', '-created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='monitoring__status_c3c74f_idx'), models.Index(fields=['requested_by', 'status'], name='monitoring__request_474304_idx')],
            },
        ),
    ]
